name: Notify Site Repo

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger site rebuild
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SITE_DISPATCH_TOKEN }}
          repository: boringops-hq/boringops-hq.github.io
          event-type: rebuild-site
